release:
  - head-branch: "^release/"

feature:
  - head-branch: "^feature/"

optimisation:
  - head-branch: "^optimisation/"

hotfix:
  - head-branch: "^hotfix/"

fix:
  - head-branch: "^fix/"

dependencies:
  - head-branch:
      - "^dependencies/"
      - "^dependabot/"
