release:
  - head-branch: "^release/"
  - head-branch: "^changeset-release/main"

feature:
  - head-branch: "^feature/"

enhancement:
  - head-branch: 
     - "^optimisation/"
     - "^improvement/"
     - "^enhancement/"

hotfix:
  - head-branch: "^hotfix/"

fix:
  - head-branch: "^fix/"

dependencies:
  - head-branch:
      - "^dependencies/"
      - "^dependabot/"
