changelog:
  exclude:
    labels:
      - release
  categories:
    - title: New Features ✨
      labels:
        - feature
    - title: Improvements 🖌️
      labels:
        - enhancement
    - title: Fixes 🐛
      labels:
        - hotfix
        - fix
    - title: Dependencies ⬆️
      labels:
        - dependencies
    - title: Other
      labels:
        - "*"
