name: Release
on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
        description: Version in format x.x.x

jobs:
  tag:
    name: Create tag
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag.outputs.tag }}
    steps:
      - uses: actions/checkout@v6
      - name: Tag
        shell: bash
        id: tag
        run: |
          set -x
          if ! git ls-remote --exit-code origin refs/tags/${{ inputs.version }} >/dev/null; then
            echo "Creating tag ${{ inputs.tag }} at ${{ forgejo.ref_name }} (${{ forgejo.sha }})"
            git tag ${{ inputs.version }}
            git push origin ${{ inputs.version }}
          else
            exit 1
          fi
          echo "tag=${{ inputs.version }}" >> $FORGEJO_OUTPUT

  release:
    name: Create release
    runs-on: ubuntu-latest
    needs: [tag]
    steps:
      - uses: actions/checkout@v6
        with:
          ref: refs/tags/${{ needs.tag.outputs.tag }}
      - name: Create release notes
        uses: actions/forgejo-release@v2.12.0
        with:
          direction: upload
          tag: ${{ needs.tag.outputs.tag }}
          url: https://codeberg.org
          verbose: true # for debugging
          token: ${{ forgejo.token }}
          release-notes-assistant: true
          skip-assets: true
      # since dokploy doesn't allow deployment on tag for gitea we trigger the deployment manually for now
      - name: Deploy prod
        shell: bash
        run: |
          set -x
          curl -X POST -H "Content-Type: application/json" --data '${{ toJSON(forgejo.event) }}' ${{ secrets.DOKPLOY_WEBHOOK }}
