name: Release
on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
        description: Version in format x.x.x

jobs:
  release:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: refs/tags/${{ inputs.version }}
      - name: Create release notes
        uses: actions/forgejo-release@v2
        with:
          direction: upload
          url: https://codeberg.org
          verbose: true # for debugging
          release-notes-assistant: true
