name: ISR

on:
  workflow_dispatch:
    inputs:
      base_url:
        type: string
        default: https://lukastrombach.dev
        description: Base URL
      path:
        type: choice
        default: cv.pdf
        options:
          - cv.pdf
          - about
        required: true

jobs:
  trigger_isr:
    runs-on: ubuntu-latest
    name: Trigger ISR revalidation for ${{ format('{0}/{1}', inputs.base_url, inputs.path) }}
    steps:
      - name: Run curl
        run: |
          curl -I --header "x-prerender-revalidate: ${{ secrets.ISR_BYPASS_TOKEN }}" ${{ format('{0}/{1}', inputs.base_url, inputs.path) }}
