name: Trigger ISR

on:
  workflow_dispatch:
    inputs:
      base_url:
        type: string
        default: https://lukastrombach.dev
        description: Base URL
      path:
        type: choice
        default: cv.pdf
        description: Path
        options:
          - cv.pdf
          - about
        required: true

jobs:
  trigger_isr:
    uses: ./.github/workflows/call.isr.yml
    with:
      base_url: ${{ inputs.base_url }}
      path: ${{ inputs.path }}
    secrets: inherit
