name: Lighthouse CI

on:
  schedule:
    - cron: "0 7 * * *"
  workflow_dispatch:

jobs:
  run:
    strategy:
      fail-fast: false
      matrix:
        route: ["", "/projects", "/contact"]
        mode: ["mobile", "desktop"]
    uses: ./.github/workflows/lhci.yml
    with:
      url: https://www.lukastrombach.dev${{ matrix.route }}
      environment: production
    secrets: inherit
