name: Lighthouse CI

on:
  schedule:
    - cron: "0 7 * * *"
  workflow_dispatch:

jobs:
  run:
    strategy:
      fail-fast: false
      matrix:
        route: ["", "/projects", "/contact"]
    uses: ./.github/workflows/lhci.yml
    with:
      url: https://www.lukastrombach.dev${{ matrix.route }}
      config-path: ./lighthouserc.Production.json
    secrets: inherit
